-- Manyplay Black Market - CREATOR CLIENT
-- Ouvre le menu admin UI, gère l'interaction, callbacks

RegisterNetEvent("manyplay_bm_creator:openui", function()
    SetNuiFocus(true, true)
    SendNUIMessage({ action = "openCreator" })
    TriggerServerCallback("manyplay_bm_creator:getConfig", function(cfg)
        SendNUIMessage({ action = "setConfig", config = cfg })
    end)
end)

RegisterNUICallback("closeCreator", function(_, cb)
    SetNuiFocus(false, false)
    cb("ok")
end)

RegisterNUICallback("updateMarket", function(data, cb)
    TriggerServerEvent("manyplay_bm_creator:updateMarket", data.id, data.market)
    cb("ok")
end)
RegisterNUICallback("addMarket", function(data, cb)
    TriggerServerEvent("manyplay_bm_creator:addMarket", data.marketId, data.market)
    cb("ok")
end)
RegisterNUICallback("removeMarket", function(data, cb)
    TriggerServerEvent("manyplay_bm_creator:removeMarket", data.marketId)
    cb("ok")
end)
RegisterNUICallback("updateWhitelist", function(data, cb)
    TriggerServerEvent("manyplay_bm_creator:updateWhitelist", data.marketId, data.whitelist)
    cb("ok")
end)